# Generated by Django 6.0 on 2026-01-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(max_length=300)),
                ('journal', models.CharField(max_length=300)),
                ('year', models.PositiveIntegerField()),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
