# Generated by Django 6.0 on 2026-01-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='МЦ Приморски', max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='site/')),
                ('logo_width', models.PositiveIntegerField(default=140, help_text='Logo width in pixels')),
                ('primary_color', models.CharField(default='#0a6ebd', help_text='Main theme color (HEX)', max_length=20)),
                ('header_height', models.PositiveIntegerField(default=80)),
                ('sticky_header', models.BooleanField(default=True)),
                ('show_hero', models.BooleanField(default=True)),
                ('show_doctors', models.BooleanField(default=True)),
                ('show_publications', models.BooleanField(default=True)),
                ('show_booking_cta', models.BooleanField(default=True)),
                ('homepage_intro', models.TextField(default='Съвременна медицина с грижа за пациента.')),
                ('clinic_phone', models.CharField(blank=True, max_length=50)),
                ('clinic_email', models.EmailField(blank=True, max_length=254)),
                ('footer_text', models.TextField(default='© Медицински център Приморски')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
