services:
  - type: web
    name: mcprimorski
    env: python
    region: frankfurt
    plan: free

    buildCommand: |
      pip install -r requirements.txt
      cd clinic_site
      python manage.py collectstatic --noinput
      python manage.py migrate

    startCommand: |
      cd clinic_site
      gunicorn clinic_site.wsgi:application

    envVars:
      - key: DEBUG
        value: "False"


