# Generated by Django 6.0 on 2026-01-02 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0002_specialty_doctor_specialties'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.specialty'),
        ),
    ]
