# Generated by Django 6.0 on 2026-01-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='doctors/')),
                ('bio', models.TextField()),
                ('education', models.TextField()),
                ('qualifications', models.TextField()),
                ('experience', models.TextField()),
            ],
        ),
    ]
