# Generated by Django 6.0 on 2026-01-02 22:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_specialty_doctor_specialties'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)])),
                ('is_open', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Appointment window',
                'verbose_name_plural': 'Appointment windows',
                'ordering': ['-date', 'doctor', 'start_time'],
            },
        ),
    ]
